### ISSUE TITLE
Can't generate the manifest.json with vite-plugin-symfony

### ISSUE THREAD

**Issue by JohannDumoulin** [owlsdepartment/vite-plugin-dev-manifest#3]
I'm trying to use viteJs within a symfony project so I've install the [pentatrion/vite-bundle](https://packagist.org/packages/pentatrion/vite-bundle)

I need a `manifest.json` to be built on dev server but, because of the [vite-plugin-symfony](https://github.com/lhapaipai/vite-plugin-symfony), the `manifest.json` can't be created properly.

vite-plugin-symfony delete the `manifest.json` created by vite-plugin-dev-manifest :

```
devServer.httpServer?.once("listening", () => {
   ...

   existsSync(buildDir) && emptyDir(buildDir);

   ...
}
```

The only fix I found is to add a `setTimeout()` on the `writeFileSync()`  to generate the `manifest.json` after the clear:
```
setTimeout(() => {
   writeFileSync(path.resolve(outputDir, `${manifestName}.json`), JSON.stringify(manifest, null, '\t'));
}, 10)
```

**Is there a configuration i missed or is this a design issue ?**

**Comment by przyb** [comment]
@JohannDumoulin thanks for the catch. That's actually a really interesting case of a conflict between plugins. I've reviewed [vite-plugin-symfony](https://github.com/lhapaipai/vite-plugin-symfony)'s source code and it's unfortunate, that there's no option to disable the directory cleanup or whitelist some files that should be kept. It would also be cool if Vite had provided a way to control the order of listener execution so that we could control it on our side. Using `setTimeout` is a clever way to defer the execution however it might harm integration with other plugins that might expect the manifest's creation at that certain point, so I'm not sure about integrating this as the default behavior. We'll think about a way to address this problem in a more universal manner. In the meantime: have you tried to change the order of plugin registration, so that the `vite-plugin-symfony` is hooked before `vite-plugin-dev-manifest`? I don't have time at the moment to set up a test bench to test it out, but that's something I would try.

**Comment by JohannDumoulin** [comment]
@przyb thanks for considering my case !
I agree with you that using `setTimeout` isn't the best way to handle it

I've tried to register the `vite-plugin-symfony` before the `vite-plugin-dev-manifest` but that doesn't resolve the problem.

**Comment by przyb** [comment]
@JohannDumoulin thanks for your reply. We'll consider how to best approach this problem. We'll keep you posted, this might take some time however and I can't guarantee any time frame, as Christmas and the new year is near which keeps us a bit busy. We're also open to considering merging a PR for that however we're looking for a solution more bulletproof than just a `setTimeout` :)

**Comment by F0rsaken** [comment]
@JohannDumoulin turns out that `vite-plugin-symfony` is registered as `post` plugin so I also added `enforce: "post"`. Changing the order of plugins should help now, but if not, I added also `delay` config option, that adds `setTimeout`

Let me know if it helped! (new changes in version `1.1.0`)

**Comment by hdasdoria** [comment]
Thanks for your fix, works perfectly now! :+1:

**Comment by F0rsaken** [comment]
glad I could help ^^

**Comment by nlemoine** [comment]
@F0rsaken, actually, I don't think this issue was caused by plugin order. It was very probably caused by `vite-plugin-symfony` emptying the `outDir` in dev mode. After a long discussion, the author agreed to remove that behavior.

This means that from `vite-plugin-symfony@6.4.4`, the delay option in your plugin might not be needed anymore.

(More details on the referenced link above)
